import type { Metadata } from "next";
import "./globals.css";
import { poppins } from '../ui/fonts'

export const metadata: Metadata = {
  title: "url-shortening-api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${poppins.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
